name: Update submodule

on: 
  repository_dispatch:
    type: [update_submodule]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # 允许 git-auto-commit 的 GITHUB_TOKEN 写入仓库
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update submodule
      run: git submodule update --remote --recursive
    - name: Commit submodule update
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update source file pointer
        file_pattern: 'sources/shared'